default:
  image: python:3.7
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test1:
  stage: test
  tags:
    - shell
  script:
    - echo "Testing"
    - cd /Users/macbookp/Desktop/Duke/Semester2023spring/fintech512/GroupProject
    - pytest
    # - cd tests
    # - python3 -m unittest test_db.py

# test_auth:
#   stage: test
#   script:
#     - cd tests
#     - python3 -m unittest test_auth.py
#     - echo "Authorization successfully running"

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production