default:
  image: python:3.7
build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"

test_db:
  stage: tests
  script:
    - echo "Database successfully running"

test_auth:
  stage: tests
  script:
    - echo "Authorization successfully running"
    - sleep 20

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
#   environment: production